---
- name: Prometheus Alertmanager
  hosts: all
  sources:
  - name: alertmanager
    ansible.eda.alertmanager:
      host: 0.0.0.0
      port: 5001
  rules:
  - name: Configuration Changed
    condition: true
    action:
      print_event:
