---
- name: Prometheus Alertmanager
  hosts: all
  sources:
  - name: alertmanager
    ansible.eda.alertmanager:
      host: 0.0.0.0
      port: 5000
  rules:
  - name: Configuration Changed
    condition: true
    action:
      debug:
        Event: {{ event | to_nice_json }}
        Vars: {{ vars | to_nice_json }}
        Env: {{ env }}
