---
- name: Hello Events  
  hosts: all
  sources:
  - name: kafka
    ansible.eda.kafka:
      host: kafkaworkshop.ansible.test
      port: 9092
      topic: eda
  rules:
  - name: Send email
    condition: event.body.eda is defined
    action:
      run_job_template:
        name: email
        organization: Default
