---
- name: Hello Events  
  hosts: localhost
  sources:
  - name: kafka
    ansible.eda.kafka:
      host: edaworkshop.ansible.test
      port: 9092
      topic: eda
  rules:
  - name: Send email
    condition: event.payload.message != ""
    action:
      run_job_template:
        name: email
        organization: Default
