---
- name: Prometheus Alertmanager
  hosts: all
  sources:
  - name: alertmanager
    ansible.eda.alertmanager:
      host: 0.0.0.0
      port: 5001
  rules:
  - name: Configuration Changed
    condition: event.alert.labels.alertname == "TLSCertificateExpiring" and event.alert.status == "firing" and event.alert.labels.instance == "https://rhel7.wkshop.lab"
    action:
      run_job_template:
        name: tls-certificate-expire
        organization: Default
