---
- name: Check Web Application
  hosts: all
  sources:
  - name: url_check
    ansible.eda.url_check:
      urls:
        - https://192.168.196.131
  rules:
  - name: Configuration Changed
    condition: event.payload.message != ""
    action:
      run_job_template:
        name: Recover
        organization: Default
