---
- name: Check Web Application
  hosts: all
  sources:
  - name: url_check
    ansible.eda.url_check:
      urls:
        - https://www.google.com
      delay: 10
  rules:
  - name: 如果回應不是200，則記錄事件
    condition: event.url_check.status == "down"
    action:
      run_job_template:
        name: Recover
        organization: Default
